stages:
  - aws-login
  - docker-ecr
  - kubernetes

login:
  stage: aws-login
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws eks list-clusters

starting:
  stage: aws-login
  script:
    - echo "Iniciando servidor"

docker:
  stage: docker-ecr
  script: echo "Logando no Docker"

kubectl:
  stage: kubernetes
  script: echo "Configurando o Kubernetes"
