apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-api
  labels:
    app: nestjs-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs-api
  template:
    metadata:
      labels:
        app: nestjs-api
    spec:
      containers:
        - name: nestjs-api
          image: 471112647960.dkr.ecr.us-east-2.amazonaws.com/nestjs-api-docker:cfcfff219911a6de2c7bad0187024ec33be41bd8
          ports:
            - containerPort: 3000
