name: Deploy to EKS
on:
  push:
    branches:
      - master
jobs:
  deploy-aws-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Iniciando job
        run: echo "Iniciando job"

      - name: Fazer o login na AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List Clusters
        run: aws eks list-clusters

      - name: Fazer o login no ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Build e tag do Docker e push para o Amazon ECR
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build --pull --rm -f ./app/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG "app"
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Descriptografar arquivo kubeconfig
        env:
          KUBECONFIG_PASSPHRASE: ${{ secrets.KUBECONFIG_PASSPHRASE }}
        run: |
          mkdir ./secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$KUBECONFIG_PASSPHRASE" --output ./secrets/kubeconfig ./app/k8s/kubeconfig.gpg

      - name: Testar kubeconfig
        run: |
          cat ./secrets/kubeconfig

      - name: Criar arquivo config do Kubernetes
        run: mkdir -p ~/.kube && mv ./app/k8s/kubeconfig ~/.kube/config

      - name: Atualizar informações do kubeconfig
        env:
          EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Testar Kubernetes
        run: |
          kubectl config get-contexts
          kubectl get pods

      - name: Aplicar o arquivo deployment.yaml com a nova imagem
        run: echo "Aplicar o arquivo deployment.yaml com a nova imagem"
