name: Deploy to EKS
on:
  push:
    branches:
      - master
jobs:
  deploy-aws-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Iniciando job
        run: echo "Iniciando job"

      - name: Fazer o login na AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List Clusters
        run: aws eks list-clusters

      - name: Fazer o login no ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build e tag do Docker e push para o Amazon ECR
        run: |
          docker build --pull --rm -f "app\Dockerfile" -t 471112647960.dkr.ecr.us-east-2.amazonaws.com/nestjs-api-docker:0.1.8 "app"
          docker push 471112647960.dkr.ecr.us-east-2.amazonaws.com/nestjs-api-docker:0.1.8

      - name: Upload da imagem Docker para ECR
        run: echo "Upload da imagem Docker para ECR"

      - name: Configurar o Kubernetes
        run: echo "Configurar o Kubernetes"

      - name: Aplicar o arquivo deployment.yaml com a nova imagem
        run: echo "Aplicar o arquivo deployment.yaml com a nova imagem"
