name: Deploy to EKS
on:
  push:
    branches:
      - master
jobs:
  deploy-aws-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Iniciando job
        run: echo "Iniciando job"

      - name: Fazer o login na AWS
        run: echo "Fazer o login na AWS"

      - name: Fazer o login no ECR
        run: echo "Fazer o login no ECR"

      - name: Build do Docker
        run: echo "Build do Docker"

      - name: Upload da imagem Docker para ECR
        run: echo "Upload da imagem Docker para ECR"

      - name: Configurar o Kubernetes
        run: echo "Configurar o Kubernetes"

      - name: Aplicar o arquivo deployment.yaml com a nova imagem
        run: echo "Aplicar o arquivo deployment.yaml com a nova imagem"
